### ISSUE TITLE
Readthedocs API module is empty

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_workflow#132]
The build is passing ok, both here and on the readthedocs web interface, but I'm not seeing the expected content. 

The main page is blank, but I expect this, what confuses me is that the [module API](https://pyiron-workflow.readthedocs.io/en/latest/source/indices.html) gives an empty `index` and a 404 for the `module index`.

Looking at the [api docs](https://github.com/pyiron/pyiron_workflow/blob/main/docs/source/indices.rst) and everything leading I'm not seeing and differences that should break things compared to, e.g., the same stuff on `pyiron_contrib` (where the [API docs](https://pyiron-contrib.readthedocs.io/en/latest/py-modindex.html) are working fine). What am I missing?

**Comment by niklassiemer** [comment]
One difference I see is in the `readthedocs.yml` file. On contrib it includes an additional `pip install .` which might lead to all the paths known to the apidoc module?

**Comment by liamhuber** [comment]
Perfect, that was exactly the issue -- thank you @niklassiemer!
