### ISSUE TITLE
Some syntax ideas for the workflow class

### ISSUE THREAD

**Issue by JNmpi** [pyiron/pyiron_workflow#15]
@liamhuber, thanks for pushing forward the workshop class. I had a look at airflow and liked some of the expressions they use to define nodes (the call them tasks) and workflows (call DAG).

- The node returns a dictionary like: `return {'y': x + 1}` providing a simple and python conform way to name the output variables. Using this notation would allow us to avoid defining the label name in the node decorator statement.

- They have a concept called *operator* which provides a template for certain node types. An example is a node generator (operator) for running bash scripts: 

            my_bash_node = BashOperator(
                    task_id="sleep",
                    depends_on_past=False,
                    bash_command="sleep 5",
                    retries=3,
                )

- Such node templates could be used to e.g. run executables in different environments, to construct executor instances, databases etc.

- To link nodes they use the `>>` operator. Possible examples could be:

        project_node >> [structure_node.input.project, lammps_node.input.engine]
        [node1, node2] >> node3 >> node4     # for fast nodes with a single input and output

- The construction of the workflow could be done within a *with* statement:

      with Workflow(label='my_workflow', 
                               author='name', 
                               "retries": 1) as wf:

             node_sleep = BashOperator(
                    task_id="sleep",
                    depends_on_past=False,
                    bash_command="sleep 5",
                    retries=3,
                )
            wf.add_node(node_sleep)
            ...

**Comment by liamhuber** [comment]
- Output is accessible as a dict, even though it still comes in channels
- Wound up using `>>`, but most of the time flow is anyhow automated
- Ease-of-use is ever evolving, but I'd say our decorators, node injection, and other creators (`Workflow.create.for_node`, etc.) surpass everything to do with operators discussed here
- We still don't use `with`, but the content on that topic here doesn't warrant keeping the issue open; we'll keep looking for convenient/powerful`with` use cases
