### ISSUE TITLE
Storage (& DB & information management...): git-copy `tinybase` here

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_workflow#161]
Per the discussion with me, @pmrv, @JNmpi this morning, let's "git-copy" `tinybase` out of `pyiron_contrib` and include it (just the whole thing for now) as a sub-module here, i.e. `pyiron_contrib.tinybase::tinydata --> pyiron_workflow.tinybase`.

This way it can be leveraged without the heavy import cost of contrib.

**Comment by niklassiemer** [comment]
Fine with me, another solution could be to not import any submodules of contrib by default, i.e. only import stuff from contrib if it really wanted by an explicit call (of course this only reduces the import time, not the number of possible dependencies)
