### ISSUE TITLE
Using duplicate names in input and output does not raise error 

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_workflow#4]
Sorry for opening so many issues one after another. I would love to have some feedback but don't feel pressure to change something. This issue could be related to [this one](https://github.com/pyiron/pyiron_workflow/issues/5).

```python
@single_value_node()
def get_y(x):
    result = x * 2
    return result

@single_value_node()
def get_z(x):
    result = x * 3
    return result

wf = Workflow('MyWorkflow')
wf.add(get_y())
wf.add(get_z())

wf.draw()
```
This gives the following diagram:

<img width="548" alt="Screenshot 2023-09-24 at 13 20 37" src="https://github.com/pyiron/pyiron_contrib/assets/37879103/4fe19937-1543-4eeb-b9c0-15c48c049055">

However, both `x` and `result` refer to different variables, so the arrows should not point to the same variables. Actually if dangling inputs and outputs are not allowed to be duplicated, as I suggested [in this issue](https://github.com/pyiron/pyiron_contrib/issues/864), the problem above would be resolved.

**Comment by liamhuber** [comment]
I transferred the workflow content from a branch containing the fix for this.
