### ISSUE TITLE
How do I return multiple args with multiple type hints?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_workflow#525]
This works:
```python
@Workflow.wrap.as_function_node("X", "Y")
def f(a, b):
    return a + b, a * b
```

But not this:

```python
@Workflow.wrap.as_function_node("X", "Y")
def f(a, b) -> (float, float):
    return a + b, a * b
```

The second one is now allowed with `semantikon`, and would be super helpful if it would work in `pyiron_workflow`.

**Comment by liamhuber** [comment]
That's because your second example isn't a proper python return type hint. You need to hint it as a tuple, not provide a tuple of hints:

```python
from pyiron_workflow import Workflow

@Workflow.wrap.as_function_node("X", "Y")
def f(a, b) -> tuple[float, float]:
    return a + b, a * b

f.preview_outputs()
>>> {'X': float, 'Y': float}

```

IMO, the second one should not be allowed with `semantikon`. Rather we'd want something like `tuple[u(float, "length"), u(float, "width")]` for consistency with the rest of python.

**Comment by liamhuber** [comment]
Unless it is a valid hint format. I'm actually suddenly less confident of that. Then we could modify pwf so it takes a tuple of hints in addition to a hint of tuple

**Comment by samwaseda** [comment]
Actually it was [your idea](https://github.com/pyiron/semantikon/pull/4#pullrequestreview-2311364341) to simply put them in a tuple, if I understood it correctly...

**Comment by samwaseda** [comment]
ChatGPT indeed says it's not a valid type hint, so I'm gonna turn it back.

**Comment by liamhuber** [comment]
> Actually it was [your idea](https://github.com/pyiron/semantikon/pull/4#pullrequestreview-2311364341) to simply put them in a tuple, if I understood it correctly...

Ah, my bad. I meant you didn't need `typing.Tuple` or whatever but could just use `buitins.tuple`. I was sloppy with my language though, so that's 100% on me.

**Comment by samwaseda** [comment]
But isn't `typing.Tuple` exactly the same as `tuple`? I mean, it's up to the user to decide which one to use?

**Comment by liamhuber** [comment]
Is a beige Porsche the same as a cherry red Porsche? It's true they will both get us where we're going, but I know unambiguously which one I want more 😂  This was the only intent of that original comment

**Comment by liamhuber** [comment]
(also since `tuple` is builting, if we consistently use `list`, `tuple`, `dict` for our hints, we can reduce imports, which is also merely stylistic but at least a slightly more concrete advantage in terms of code length/complexity)
